# Generated by Django 2.2.24 on 2022-01-12 07:19

from django.db import migrations
import phonenumbers


def normalize_phone_numbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        parsed_phonenumber = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        flat.owner_pure_phone = parsed_phonenumber
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_auto_20220112_0931'),
    ]

    operations = [
        migrations.RunPython(normalize_phone_numbers)
    ]
